### ISSUE TITLE
could not find function with TreeSearch 0.4.0

### ISSUE THREAD

**Issue by computingmachine** [ms609/TreeSearch#57]
Hi,

I update the package to version 0.4.0 . But it doesn't work. Below is the error

> library(TreeSearch)
Warning message:
package ‘TreeSearch’ was built under R version 3.5.3 
> SampleOne(1:10,len=10)
Error in SampleOne(1:10, len = 10) : could not find function "SampleOne"

**Comment by ms609** [comment]
Sorry you've hit this issue. 

Some functions have been calved off from 'TreeSearch' into the general utility package 'TreeTools'.

First update the 'TreeTools' package with `update.packages('TreeTools')` (this should have happened automatically when you updated 'TreeSearch', but you never know), then call `library(TreeTools)` before `SampleOne`.
