### ISSUE TITLE
Loading trees

### ISSUE THREAD

**Issue by EunokLee** [ms609/TreeSearch#93]
Hi Martin,

My name is Eunok Lee from the Westmead Institute for Medical Research. I am trying to load the tree using ape and phytool packages and I ran into the issues below:

1. When I tried to load my phylogenetic tree using read.tree(mytree.newick), I found that some tip labels were removed. When I opened the same newick file in text, I could see the tip label that I am interested in. I reinstalled the ape package and re-loaded in R, but the same problem occurred.... Could you help me how to fix this issue?

2. Due to the problem above, I tried using phytools::read.newick().  This does import the tree with all the tip labels; however, the tip label is only showing up to 22 characters. What should do to make the tip label to display the tip labels in a full character length?

Thank you and I look forward to your advice!

With kind regards,

Eunok

**Comment by ms609** [comment]
Hi Eunok, thanks for your message!  I think I'd need to see your newick file to diagnose the issue.  Would you be happy to send it either as an attachment here, or via e-mail?  Cheers, Martin

**Comment by EunokLee** [comment]
Hi Martin,

Thank you for your message. Yes, I found out that the newick input tree was the problem….

Thank you again for the message!

-Eunok
